# This is a basic workflow to help you get started with Actions

name: Build And Deploy Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ revamp/gui ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  SERVER: ${{ secrets.STAGING_SERVER }}
  BOT_ID: ${{ secrets.STAGING_BOT_ID }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
        env:
          API_URL: ${{secrets.STAGING_API_URL}}
          SOCKET_URL: ${{secrets.STAGING_SOCKET_URL}}
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Change to project Bitzenius Dev
        uses: w9jds/firebase-action@master
        with:
          args: use bitzenius-staging
        env:
          FIREBASE_TOKEN: ${{secrets.STAGING_FIREBASE_TOKEN}}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:bitzenius-staging-2306a
          path: dist
        env:
          FIREBASE_TOKEN: ${{secrets.STAGING_FIREBASE_TOKEN}}
