# This is a basic workflow to help you get started with Actions
 
name: Build And Deploy Dev
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev/dashboard ]
 
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          repository: ${{github.repository}}
          ref: dev/dashboard
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Change to project Zokubot Dev
        uses: w9jds/firebase-action@master
        with:
          args: use zokutrade-dev
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:zokutrade-dev
          path: dist
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}